export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const SORT_TASKS_DESC = 'SORT_TASKS_DESC';
export const SORT_TASKS_ASC = 'SORT_TASKS_ASC';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SAVE_DATE_START = 'SAVE_DATE_START';
export const SAVE_DATE_FINISH = 'SAVE_DATE_FINISH';
